apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: codependent/product-service:latest
        ports:
        - containerPort: 8080
